source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']

group :jekyll_plugins do
    gem 'jekyll-optional-front-matter'    # https://github.com/benbalter/jekyll-optional-front-matter
    gem 'jekyll-seo-tag'
end
