#!/bin/sh
localPath="$HOME/.m2/repository/org/reaktivity/rym/0.2/rym-0.2.jar"
wrappedPath=".rym/wrapper/rym-0.2.jar"
wrappedURL="https://repo.maven.apache.org/maven2/org/reaktivity/rym/0.2/rym-0.2.jar"
if [ ! -r "$wrappedPath" ]; then
if [ -r "$localPath" ]; then
echo $wrappedPath not found, copying from $localPath
mkdir -p `dirname $wrappedPath`
cp $localPath $wrappedPath
else
echo $wrappedPath not found, downloading from $wrappedURL
if command -v curl > /dev/null; then
curl -o "$wrappedPath" "$wrappedURL" -f
else
echo curl missing, download failed
fi
fi
fi
java $JAVA_OPTIONS -jar "$wrappedPath" "$@"
